version: "3.8"

services:
  recommendation:
    build: .
    container_name: crafty-recommendation
    ports:
      - "8080:8080"
    environment:
      - CATALOGUE_SERVICE_URL=http://localhost:5000
    networks:
      - recommendation-network
    depends_on:
      - catalogue
    restart: unless-stopped

  # Optional: Include catalogue service for standalone testing
  catalogue:
    image: crafty-catalogue:latest
    container_name: crafty-catalogue-standalone
    ports:
      - "5000:5000"
    environment:
      - DATA_SOURCE=json
    networks:
      - recommendation-network
    profiles:
      - with-catalogue

networks:
  recommendation-network:
    driver: bridge
