version: "3.8"

services:
  catalogue:
    build: .
    container_name: crafty-catalogue
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=catalogue
      - DB_USER=user
      - DB_PASSWORD=password
      - DATA_SOURCE=${DATA_SOURCE:-json}
      - APP_VERSION=1.0.0
    networks:
      - catalogue-network
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/products"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15
    container_name: crafty-catalogue-db
    restart: always
    environment:
      - POSTGRES_DB=catalogue
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catalogue-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d catalogue"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  catalogue-network:
    driver: bridge
