version: "3.8"

services:
  frontend:
    build: .
    container_name: crafty-frontend
    ports:
      - "3000:3000"
    environment:
      - PRODUCTS_API_BASE_URI=http://localhost:5000
      - RECOMMENDATION_BASE_URI=http://localhost:8080
      - VOTING_BASE_URI=http://localhost:8086
      - NODE_ENV=production
    networks:
      - frontend-network
    depends_on:
      - catalogue
      - recommendation
      - voting
    restart: unless-stopped

  # Optional: Include all services for standalone testing
  catalogue:
    image: crafty-catalogue:latest
    container_name: crafty-catalogue-standalone
    ports:
      - "5000:5000"
    environment:
      - DATA_SOURCE=json
    networks:
      - frontend-network
    profiles:
      - full-stack

  recommendation:
    image: crafty-recommendation:latest
    container_name: crafty-recommendation-standalone
    ports:
      - "8080:8080"
    environment:
      - CATALOGUE_SERVICE_URL=http://catalogue:5000
    networks:
      - frontend-network
    depends_on:
      - catalogue
    profiles:
      - full-stack

  voting:
    image: crafty-voting:latest
    container_name: crafty-voting-standalone
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - frontend-network
    profiles:
      - full-stack

networks:
  frontend-network:
    driver: bridge
